// Remplace uniquement la section styles à la fin :
const styles = {
  page: { maxWidth: '1200px', margin: '0 auto', padding: 'clamp(4.5rem, 10vw, 6rem) 1rem 6rem', minHeight: '100vh', fontFamily: "'Inter', -apple-system, sans-serif" },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '0.8rem' },
  titre: { fontFamily: 'Georgia, serif', fontSize: 'clamp(1.6rem, 4vw, 2.8rem)', fontWeight: '900', color: '#0d0d0d', letterSpacing: '-0.02em', marginBottom: '0.4rem' },
  refresh: { color: '#aaa', fontSize: '0.78rem', fontFamily: "'Inter', sans-serif" },
  statutPill: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', borderRadius: '100px', fontSize: '0.82rem', fontWeight: '700', fontFamily: "'Inter', sans-serif", textDecoration: 'none' },
  statutDot: { width: '8px', height: '8px', borderRadius: '50%', flexShrink: 0 },
  statutEdit: { color: 'inherit', opacity: 0.6, fontSize: '0.75rem', marginLeft: '0.3rem' },
  onglets: { display: 'flex', gap: '0.4rem', marginBottom: '1.5rem', flexWrap: 'wrap' },
  onglet: { background: 'white', border: '1.5px solid #e8e8ed', padding: '0.55rem 0.9rem', borderRadius: '100px', cursor: 'pointer', fontWeight: '600', fontSize: '0.78rem', fontFamily: "'Inter', sans-serif", color: '#555' },
  ongletActif: { background: '#E63946', border: '1.5px solid #E63946', color: 'white', boxShadow: '0 4px 12px rgba(230,57,70,0.25)' },
  // ✅ Stats 2x2 sur mobile
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.8rem', marginBottom: '1.5rem' },
  stat: { background: 'white', borderRadius: '14px', padding: '1rem', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' },
  statIcon: { fontSize: '1.3rem', marginBottom: '0.4rem' },
  statNum: { fontSize: '1.5rem', fontWeight: '900', color: '#0d0d0d', fontFamily: "'Inter', sans-serif", letterSpacing: '-0.02em' },
  statLabel: { color: '#888', marginTop: '0.2rem', fontSize: '0.75rem', fontFamily: "'Inter', sans-serif" },
  sectionTitle: { fontFamily: 'Georgia, serif', fontSize: 'clamp(1.1rem, 2.5vw, 1.5rem)', color: '#0d0d0d', marginBottom: '0.8rem', fontWeight: '700' },
  // ✅ Menu 2x2 sur mobile
  menuGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.8rem', marginBottom: '1.5rem' },
  menuCard: { background: 'white', borderRadius: '16px', padding: '1.2rem 1rem', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', textDecoration: 'none', color: '#0d0d0d', textAlign: 'center', border: '1.5px solid #f0f0f0' },
  menuIcon: { fontSize: '2rem', marginBottom: '0.5rem' },
  menuTitre: { fontFamily: 'Georgia, serif', fontSize: '0.95rem', fontWeight: '700', marginBottom: '0.2rem', color: '#0d0d0d' },
  menuSub: { fontSize: '0.75rem', fontFamily: "'Inter', sans-serif" },
  empty: { background: 'white', borderRadius: '14px', padding: '2rem', textAlign: 'center', color: '#aaa', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', marginBottom: '1rem', fontFamily: "'Inter', sans-serif", fontSize: '0.88rem' },
  graphCard: { background: 'white', borderRadius: '16px', padding: '1.2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', marginBottom: '1.5rem' },
  barChart: { display: 'flex', alignItems: 'flex-end', justifyContent: 'space-around', height: '140px', gap: '0.2rem' },
  barWrapper: { display: 'flex', flexDirection: 'column', alignItems: 'center', cursor: 'pointer', flex: 1 },
  barValue: { fontSize: '0.65rem', fontWeight: '700', color: '#0d0d0d', marginBottom: '0.2rem', fontFamily: "'Inter', sans-serif" },
  barContainer: { width: '100%', height: '90px', display: 'flex', alignItems: 'flex-end', justifyContent: 'center' },
  bar: { width: '60%', borderRadius: '6px 6px 0 0', transition: 'all 0.35s ease', minHeight: '4px' },
  barLabel: { fontSize: '0.65rem', marginTop: '0.3rem', fontFamily: "'Inter', sans-serif" },
  barDate: { fontSize: '0.58rem', color: '#bbb', fontFamily: "'Inter', sans-serif" },
  // ✅ Tableau mobile — cartes au lieu de grille
  tableWrap: { background: 'white', borderRadius: '16px', overflow: 'hidden', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', marginBottom: '1.5rem' },
  tableHeader: { display: 'none' }, // caché sur mobile
  tableRow: { display: 'flex', flexDirection: 'column', padding: '1rem', borderBottom: '1px solid #f5f5f7', fontSize: '0.85rem', fontFamily: "'Inter', sans-serif", gap: '0.3rem' },
  codeCmd: { fontWeight: '800', color: '#0d0d0d', fontFamily: 'Georgia, serif', fontSize: '0.95rem' },
  cellTxt: { color: '#444', fontSize: '0.82rem' },
  deleteBtn: { background: '#fff0f0', color: '#c00', border: 'none', padding: '0.35rem 0.6rem', borderRadius: '8px', cursor: 'pointer', fontWeight: '700', fontSize: '0.82rem', alignSelf: 'flex-start' },
  addBtn: { background: '#E63946', color: 'white', padding: '0.6rem 1.2rem', borderRadius: '100px', textDecoration: 'none', fontWeight: '700', fontSize: '0.82rem', fontFamily: "'Inter', sans-serif" },
  periodeSwitch: { display: 'flex', gap: '0.4rem', marginBottom: '1.5rem', flexWrap: 'wrap' },
  periodeBtn: { background: 'white', border: '1.5px solid #e8e8ed', padding: '0.5rem 1rem', borderRadius: '100px', cursor: 'pointer', fontWeight: '600', fontSize: '0.78rem', fontFamily: "'Inter', sans-serif", color: '#555' },
  periodeBtnActif: { background: '#0d0d0d', border: '1.5px solid #0d0d0d', color: 'white' },
  totalGlobal: { background: 'linear-gradient(135deg, #1a1a2e, #2d1a1a)', borderRadius: '16px', padding: '1.5rem', textAlign: 'center', marginBottom: '1.2rem', color: 'white' },
  totalGlobalLabel: { fontFamily: "'Inter', sans-serif", fontSize: '0.75rem', color: 'rgba(255,255,255,0.6)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.4rem' },
  totalGlobalVal: { fontFamily: 'Georgia, serif', fontSize: 'clamp(1.8rem, 4vw, 3rem)', fontWeight: '900', color: '#FFB703', letterSpacing: '-0.02em' },
  totalGlobalSub: { fontFamily: "'Inter', sans-serif", fontSize: '0.75rem', color: 'rgba(255,255,255,0.5)', marginTop: '0.4rem' },
  revenuGrid: { display: 'grid', gridTemplateColumns: '1fr', gap: '1rem', marginBottom: '1.5rem' },
  revenuCard: { background: 'white', borderRadius: '16px', padding: '1.2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', border: '1.5px solid #f0f0f0' },
  revenuCardHeader: { display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '1rem' },
  revenuLogo: { width: '40px', height: '40px', borderRadius: '10px', objectFit: 'contain', border: '1px solid #e8e8ed', padding: '3px', background: 'white', flexShrink: 0 },
  especesIconGrand: { width: '40px', height: '40px', borderRadius: '10px', background: '#f0faf5', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.4rem', border: '1px solid #b7e4c7', flexShrink: 0 },
  revenuNom: { fontFamily: 'Georgia, serif', fontWeight: '700', fontSize: '0.95rem', color: '#0d0d0d' },
  revenuNb: { fontFamily: "'Inter', sans-serif", fontSize: '0.75rem', color: '#aaa', marginTop: '0.2rem' },
  revenuMontant: { fontFamily: "'Inter', sans-serif", fontWeight: '900', fontSize: '1.5rem', color: '#0d0d0d', letterSpacing: '-0.02em', marginBottom: '0.8rem' },
  revenuFcfa: { fontSize: '0.85rem', fontWeight: '500', color: '#aaa' },
  barreProgres: { height: '6px', background: '#f0f0f0', borderRadius: '100px', marginBottom: '0.4rem', overflow: 'hidden' },
  barreProgresInner: { height: '100%', borderRadius: '100px', transition: 'width 0.5s ease' },
  revenuPct: { fontFamily: "'Inter', sans-serif", fontSize: '0.75rem', color: '#888', fontWeight: '600' },
  jourDetail: { background: '#f9f9f9', borderRadius: '12px', padding: '1rem', marginTop: '1rem', border: '1.5px solid #e8e8ed' },
  jourDetailTitre: { fontFamily: 'Georgia, serif', fontWeight: '700', fontSize: '0.85rem', color: '#0d0d0d', marginBottom: '0.8rem' },
  jourDetailGrid: { display: 'flex', flexDirection: 'column', gap: '0.4rem' },
  jourDetailItem: { display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.3rem 0' },
  searchBar: { display: 'flex', alignItems: 'center', background: 'white', borderRadius: '50px', padding: '0.6rem 1.2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.08)', border: '1.5px solid #e0e0e0', gap: '0.6rem', marginBottom: '1.2rem' },
  searchInput: { flex: 1, border: 'none', outline: 'none', fontSize: '0.9rem', background: 'transparent', fontFamily: "'Inter', sans-serif" },
  clearBtn: { background: '#f0f0f0', border: 'none', borderRadius: '50%', width: '26px', height: '26px', cursor: 'pointer', fontWeight: '700', fontSize: '0.75rem' },
  caisseBanniere: { background: 'linear-gradient(135deg, #f3e5f5, #ede7f6)', border: '1.5px solid #ce93d8', borderRadius: '14px', padding: '1rem', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.8rem', color: '#6a1b9a' },
  caisseCard: { background: 'white', borderRadius: '16px', padding: '1.2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.07)' },
  validerBtn: { background: 'linear-gradient(135deg, #2D6A4F, #40916c)', color: 'white', border: 'none', padding: '0.9rem 1.2rem', borderRadius: '100px', fontWeight: '700', cursor: 'pointer', width: '100%', fontSize: '0.88rem', fontFamily: "'Inter', sans-serif", boxShadow: '0 4px 12px rgba(45,106,79,0.28)' },
  remiseBanniere: { background: 'linear-gradient(135deg, #fffbf0, #fff8e7)', border: '1.5px solid #FFB703', borderRadius: '14px', padding: '1rem', marginBottom: '1.2rem', display: 'flex', alignItems: 'center', gap: '0.8rem', color: '#b37a00' },
  remiseCard: { background: 'white', borderRadius: '16px', padding: '1.2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.07)', border: '1.5px solid #FFB703' },
  remiseAvatar: { width: '40px', height: '40px', borderRadius: '50%', background: '#fff8e7', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', border: '1.5px solid #FFB703', flexShrink: 0 },
  confirmerRemiseBtn: { background: 'linear-gradient(135deg, #FFB703, #f59e00)', color: '#1A1A2E', border: 'none', padding: '0.9rem 1.2rem', borderRadius: '100px', fontWeight: '800', cursor: 'pointer', width: '100%', fontSize: '0.88rem', fontFamily: "'Inter', sans-serif", boxShadow: '0 4px 12px rgba(255,183,3,0.35)', marginTop: '0.8rem' },
  separateur: { height: '1.5px', background: '#e8e8ed', margin: '0 0 1.5rem 0', borderRadius: '100px' },
  confirmBox: { background: 'linear-gradient(135deg, #fffbf0, #fff8e7)', border: '1.5px solid #FFB703', borderRadius: '12px', padding: '1rem', marginTop: '0.8rem' },
  confirmTitre: { fontWeight: '800', fontSize: '0.9rem', color: '#b37a00', marginBottom: '0.3rem', fontFamily: 'Georgia, serif' },
  confirmSub: { fontSize: '0.82rem', color: '#666', lineHeight: '1.6', fontFamily: "'Inter', sans-serif" },
  annulerConfirmBtn: { background: '#f0f0f0', color: '#333', border: 'none', padding: '0.8rem 1.2rem', borderRadius: '100px', fontWeight: '600', cursor: 'pointer', fontSize: '0.85rem', fontFamily: "'Inter', sans-serif", whiteSpace: 'nowrap' }
};